[pytest]

addopts =
    -v
    --browser=chromium
    --headed
    --base-url=https://tutorialsninja.com/demo/
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=reports/myreport.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results

markers =
    sanity: Sanity test cases
    regression: Regression test cases
    datadriven: Data driven test cases
    end_to_end: End to end test cases